# docker-compose.yml
#version: '3.8'

services:
  dev_env_builder:
    build:
      # Path to the directory containing the Dockerfile
      context: .
      # Explicitly name the Dockerfile if not 'Dockerfile'
      dockerfile: dockerfile
    image: cuda-py:${BUILD_TAG:-latest}